In [3]:
import numpy as np
col_vec = np.arange(0, 50, 10).reshape(5, 1)
row_vec = np.arange(0, 5).reshape(1, 5)
oned_vec = np.arange(5)
print(col_vec)
print(row_vec)
print(oned_vec)
np.dot(oned_vec, col_vec)


[[ 0]
 [10]
 [20]
 [30]
 [40]]
[[0 1 2 3 4]]
[0 1 2 3 4]


array([300])

In [5]:
try:
  np.dot(col_vec, oned_vec) # *boom*
except ValueError as e:
  print("I went boom:", e)
print(oned_vec.shape,
col_vec.shape, sep="\n")

I went boom: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)
(5,)
(5, 1)


In [8]:
np.dot(col_vec, oned_vec) # *boom*

ValueError: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

In [7]:
print(np.dot(row_vec, oned_vec))
try:
  print(np.dot(oned_vec, row_vec))
except:
  print("boom")

[30]
boom


In [64]:
row_vec = np.arange(5).reshape(1,5)
col_vec = np.arange(5).reshape(5,1)
print("REDVEK",row_vec)
print("STUPACVEK",col_vec)
print('____________')
print(np.dot(row_vec,col_vec))
print('____________')
print(np.dot(col_vec,row_vec))
print('____________')

one_vec=np.arange(5)
print(one_vec)
print("1D VEKTOR")
print(one_vec.shape,col_vec.shape)
print(np.dot(one_vec,col_vec))
print('____________')
print(row_vec.shape,one_vec.shape)
print(np.dot(row_vec,one_vec))
print('____________')
print(one_vec.shape,row_vec.shape)
#print(np.dot(one_vec,row_vec))
print('____________')
print(col_vec.shape,one_vec.shape)
#print(np.dot(col_vec,one_vec))

ROWVEC [[0 1 2 3 4]]
COLVEC [[0]
 [1]
 [2]
 [3]
 [4]]
____________
[[30]]
____________
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
____________
[0 1 2 3 4]
ONEVEC
(5,) (5, 1)
[30]
____________
(1, 5) (5,)
[30]
____________
(5,) (1, 5)
____________
(5, 1) (5,)


In [65]:
1.1+2.2==3.3

False

In [35]:
oned_vec = np.arange(5)
print(oned_vec.shape)
print(oned_vec)
oned_vec.reshape(5,1)
print(oned_vec.shape)
print(oned_vec)
#drugo=np.array([[1],[2],[3],[4],[5]])
drugo2=np.array([[1,2,3,4,5]])
print(drugo.shape)
print(np.dot(oned_vec, drugo2))

(5,)
[0 1 2 3 4]
(5,)
[0 1 2 3 4]
(5, 1)


ValueError: shapes (5,) and (1,5) not aligned: 5 (dim 0) != 1 (dim 0)

In [30]:
D = np.array([[1, 3],
[2, 5],
[2, 7],
[3, 2]])
weights = np.array([[1.5, 2.5,5.],[1., 2., 4.]])
np.dot(D,weights)

array([[ 4.5,  8.5, 17. ],
       [ 8. , 15. , 30. ],
       [10. , 19. , 38. ],
       [ 6.5, 11.5, 23. ]])