In [1]:
import numpy as np
jedinice_vektor = np.arange(5)
print(jedinice_vektor, "-->", jedinice_vektor * jedinice_vektor)
print("Umnožak:", np.dot(jedinice_vektor, jedinice_vektor))


[0 1 2 3 4] --> [ 0  1  4  9 16]
Umnožak: 30


In [4]:
vektor_red = np.arange(5).reshape(1,5)
vektor_stupac = np.arange(0, 50, 10).reshape(5, 1)
print("Vektor red:", vektor_red,
  "Vektor stupac:", vektor_stupac,
  "Umnožak 1:", np.dot(vektor_red, vektor_stupac), sep='\n')

Vektor red:
[[0 1 2 3 4]]
Vektor stupac:
[[ 0]
 [10]
 [20]
 [30]
 [40]]
Umnožak 1:
[[300]]


In [6]:
out = np.dot(vektor_stupac, vektor_red)
print("Umnožak 2:\n",out)

Umnožak 2:
 [[  0   0   0   0   0]
 [  0  10  20  30  40]
 [  0  20  40  60  80]
 [  0  30  60  90 120]
 [  0  40  80 120 160]]
