In [1]:
import numpy as np
dataset = np.array([1,5,10,10,17,20,35])
def compute_mean(data):
    return np.sum(data) / data.size
compute_mean(dataset)

np.float64(14.0)

In [2]:
def bootstrap_sample(data):
    N   = len(data)
    idx = np.arange(N)
    bs_idx = np.random.choice(idx, N,
                              replace=True)
    return data[bs_idx]

In [8]:
bsms = []
for i in range(5):
    bs_sample = bootstrap_sample(dataset)
    bs_mean = compute_mean(bs_sample)
    bsms.append(bs_mean)

    print(bs_sample, "{:5.2f}".format(bs_mean))
print("{:5.2f}".format(sum(bsms) / len(bsms)))

[ 1  1  1 10 20 10  5]  6.86
[10  5 17 35 35 20 10] 18.86
[ 5 10  5  1 10 17  5]  7.57
[20 20 10 10 17 10 17] 14.86
[10 35 10 10 10 10 10] 13.57
12.34
