In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np

X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y)

gb = GradientBoostingClassifier(
    n_estimators=150, learning_rate=0.1, max_depth=2, random_state=42)

ada = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1, random_state=42),
    n_estimators=150,
    learning_rate=0.5,
    random_state=42)

gb.fit(X_train, y_train)
ada.fit(X_train, y_train)

for name, model in [("GradientBoosting", gb), ("AdaBoost", ada)]:
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    print(f"{name} - Accuracy: {acc:.3f}")
    print(f"{name} - Confusion matrix:\n{cm}\n")

GradientBoosting - Accuracy: 0.933
GradientBoosting - Confusion matrix:
[[15  0  0]
 [ 0 14  1]
 [ 0  2 13]]

AdaBoost - Accuracy: 0.933
AdaBoost - Confusion matrix:
[[15  0  0]
 [ 0 14  1]
 [ 0  2 13]]

