In [29]:
from sklearn import datasets, linear_model, preprocessing as skpre
from sklearn import model_selection as skms
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

iris = datasets.load_iris()
(iris_train,     iris_test,
 iris_train_tgt, iris_test_tgt) = skms.train_test_split(iris.data,
                                                        iris.target,
                                                        test_size=.25)
# ukloni ' (cm)' iz imena
iris.feature_names = [fn[:-5] for fn in iris.feature_names]

iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

print("Numerical categories:", iris.target[[0, 50, 100]], sep='\n')

# kako izgleda tablica nakon OneHotEncodera
sparse = skpre.OneHotEncoder().fit_transform(iris.target.reshape(-1,1))
print("One-hot coding:", sparse[[0,50,100]].todense(), sep="\n")

encoded = pd.get_dummies(iris_df, prefix="is")
print(encoded.iloc[[0,50,100]])

target = "petal length"
X = encoded.drop(columns=[target])
y = encoded[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2=model.score(X_test,y_test)
print(f"RMSE na test skupu: {rmse:.4f}")
print(f"R2 na test skupu: {r2:.4f}")

Numerical categories:
[0 1 2]
One-hot coding:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
     sepal length  sepal width  petal length  petal width  is_setosa  \
0             5.1          3.5           1.4          0.2       True   
50            7.0          3.2           4.7          1.4      False   
100           6.3          3.3           6.0          2.5      False   

     is_versicolor  is_virginica  
0            False         False  
50            True         False  
100          False          True  
RMSE na test skupu: 0.2964
R2 na test skupu: 0.9732
